//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingByDaylight.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PingByDaylight.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PingByDaylight - Dead by Daylight Server Selector.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Americas.
        /// </summary>
        internal static string Americas {
            get {
                return ResourceManager.GetString("Americas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        internal static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Apply.
        /// </summary>
        internal static string ApplySelection {
            get {
                return ResourceManager.GetString("ApplySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PingByDaylight.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia (excluding Mainland China).
        /// </summary>
        internal static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific (Hong Kong).
        /// </summary>
        internal static string Asia_Hong_Kong {
            get {
                return ResourceManager.GetString("Asia_Hong_Kong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific (Mumbai).
        /// </summary>
        internal static string Asia_Mumbai {
            get {
                return ResourceManager.GetString("Asia_Mumbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific (Seoul).
        /// </summary>
        internal static string Asia_Seoul {
            get {
                return ResourceManager.GetString("Asia_Seoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific (Singapore).
        /// </summary>
        internal static string Asia_Singapore {
            get {
                return ResourceManager.GetString("Asia_Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific (Sydney).
        /// </summary>
        internal static string Asia_Sydney {
            get {
                return ResourceManager.GetString("Asia_Sydney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific (Tokyo).
        /// </summary>
        internal static string Asia_Tokyo {
            get {
                return ResourceManager.GetString("Asia_Tokyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome!.
        /// </summary>
        internal static string Awesome {
            get {
                return ResourceManager.GetString("Awesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block both (default).
        /// </summary>
        internal static string BlockBoth {
            get {
                return ResourceManager.GetString("BlockBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block UDP ping beacon endpoints.
        /// </summary>
        internal static string BlockPing {
            get {
                return ResourceManager.GetString("BlockPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block service endpoints.
        /// </summary>
        internal static string BlockService {
            get {
                return ResourceManager.GetString("BlockService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada (Central).
        /// </summary>
        internal static string Canada_Central {
            get {
                return ResourceManager.GetString("Canada_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string CheckingUpdates {
            get {
                return ResourceManager.GetString("CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainland China.
        /// </summary>
        internal static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China (Beijing).
        /// </summary>
        internal static string China_Beijing {
            get {
                return ResourceManager.GetString("China_Beijing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China (Ningxia).
        /// </summary>
        internal static string China_Ningxia {
            get {
                return ResourceManager.GetString("China_Ningxia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Options.
        /// </summary>
        internal static string DefaultOptions {
            get {
                return ResourceManager.GetString("DefaultOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer: WAFPHLEZ.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Support.
        /// </summary>
        internal static string DiscordSupport {
            get {
                return ResourceManager.GetString("DiscordSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Update.
        /// </summary>
        internal static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        internal static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe (Frankfurt am Main).
        /// </summary>
        internal static string Europe_Frankfurt {
            get {
                return ResourceManager.GetString("Europe_Frankfurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe (Ireland).
        /// </summary>
        internal static string Europe_Ireland {
            get {
                return ResourceManager.GetString("Europe_Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe (London).
        /// </summary>
        internal static string Europe_London {
            get {
                return ResourceManager.GetString("Europe_London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatekeep (default).
        /// </summary>
        internal static string GatekeepDefault {
            get {
                return ResourceManager.GetString("GatekeepDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛡️ Gatekeep Options.
        /// </summary>
        internal static string GatekeepOptions {
            get {
                return ResourceManager.GetString("GatekeepOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡ Latency.
        /// </summary>
        internal static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge unstable servers (recommended).
        /// </summary>
        internal static string MergeUnstable {
            get {
                return ResourceManager.GetString("MergeUnstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔧 Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version of the program..
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceania.
        /// </summary>
        internal static string Oceania {
            get {
                return ResourceManager.GetString("Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Open Hosts.
        /// </summary>
        internal static string OpenHosts {
            get {
                return ResourceManager.GetString("OpenHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hosts File Location.
        /// </summary>
        internal static string OpenHostsLocation {
            get {
                return ResourceManager.GetString("OpenHostsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Hosts File.
        /// </summary>
        internal static string ResetHosts {
            get {
                return ResourceManager.GetString("ResetHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Reset to Default.
        /// </summary>
        internal static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Select AWS Servers.
        /// </summary>
        internal static string SelectServers {
            get {
                return ResourceManager.GetString("SelectServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America (São Paulo).
        /// </summary>
        internal static string South_America_Sao_Paulo {
            get {
                return ResourceManager.GetString("South_America_Sao_Paulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple AWS servers. The system will choose the best one based on latency..
        /// </summary>
        internal static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Redirect.
        /// </summary>
        internal static string UniversalRedirect {
            get {
                return ResourceManager.GetString("UniversalRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates:.
        /// </summary>
        internal static string UpdateCheckError {
            get {
                return ResourceManager.GetString("UpdateCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get update information..
        /// </summary>
        internal static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update found, but download file is not available..
        /// </summary>
        internal static string UpdateDownloadUnavailable {
            get {
                return ResourceManager.GetString("UpdateDownloadUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string UpdateSize {
            get {
                return ResourceManager.GetString("UpdateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US East (Ohio).
        /// </summary>
        internal static string US_East_Ohio {
            get {
                return ResourceManager.GetString("US_East_Ohio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US East (N. Virginia).
        /// </summary>
        internal static string US_East_Virginia {
            get {
                return ResourceManager.GetString("US_East_Virginia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US West (N. California).
        /// </summary>
        internal static string US_West_California {
            get {
                return ResourceManager.GetString("US_West_California", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US West (Oregon).
        /// </summary>
        internal static string US_West_Oregon {
            get {
                return ResourceManager.GetString("US_West_Oregon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}
        ///Modern WPF interface with Dead by Daylight server selection
        ///Windows 10 or higher recommended..
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
